#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
echo "running dyalog mal (${STEP}) in dir ${PWD}, args: ${@}"
export WSPATH=$PWD
CLIARGS=$PWD/cliargs
rm -f $CLIARGS
touch $CLIARGS
for word in "$@"; do
    echo $word >> $CLIARGS
done
WS="${DIR}/Distribution/${STEP:-stepA_mal}.dws"
if [ $TERM = "dumb" ]; then

    ARGV=$CLIARGS mapl -b -s $WS 2>&1
else
	ARGV=$CLIARGS rlwrap -a mapl -b -s $WS 2>&1
fi
