#!/bin/bash
echo running dyalog mal in dir $PWD, args: $@
export WSPATH=$PWD
CLIARGS=$PWD/cliargs
rm -f $CLIARGS
touch $CLIARGS
for word in "$@"; do
    echo $word >> $CLIARGS
done
if [ $TERM = "dumb" ]; then
    ARGV=$CLIARGS mapl -b -s Distribution/${STEP:-stepA_mal} $1 2>&1
else
    ARGV=$CLIARGS rlwrap -a mapl -b -s Distribution/${STEP:-stepA_mal} $1 2>&1
fi
